version: "3.8"
services:

    router:
        image: yuvaltoker/adjusted-dlep:1.1.12
        #image: test-changes-dlep:1.3
        #build:
        #    context: ..
        #    dockerfile: ../dockerfiles/build-dlep-enviroment-dockerfile
        tty: true
        stdin_open: true
        depends_on: 
            - "server"
        networks:
            - net1
        environment:
            - IMPLEMENTATION=router
            - UI_PORT=3090
            - UI_HOST=sam-server
            - DISCOVERY_IFACE=eth0
            - DISCOVERY_INTERVAL=15
            - HEARTBEAT_INTERVAL=10
            - EXT_PAUSE=true
            - EXT_LID=true
        container_name: test-router
            
    modem:
        image: yuvaltoker/adjusted-dlep:1.1.12
        #image: test-changes-dlep:1.3
        tty: true
        stdin_open: true
        depends_on: 
            - "server"
        networks:
            - net1
        environment:
            - IMPLEMENTATION=modem
            - DISCOVERY_IFACE=eth0
            - HEARTBEAT_INTERVAL=10
            - EXT_PAUSE=true
            - EXT_LID=true
        container_name: test-modem

    server:
        image: samyon196/tcpsvr
        tty: true
        stdin_open: true
        networks:
            - net1
        environment:
            - PORT=3090
        container_name: sam-server


networks:
    net1:
        name: net1
        driver: bridge

