version: "3.8"
services:

    router:
        image: dlep:latest
        tty: true
        stdin_open: true
        networks:
            - net1
        environment:
            - UI_PORT=3090
            - UI_HOST=sam-server 
        volumes:
            - /home/user2/work/idf/dlep/adjusted-LL-DLEP/adjusted-DLEP:/adjusted-dlep    
        container_name: router1
            
    modem:
        image: dlep:latest
        tty: true
        stdin_open: true
        networks:
            - net1
        environment:
            - UI_PORT=3090
            - UI_HOST=sam-server
        volumes:
            - /home/user2/work/idf/dlep/adjusted-LL-DLEP/adjusted-DLEP:/adjusted-dlep 
        container_name: modem1

    server:
        tty: true
        stdin_open: true
        networks:
            - net1
        image: samyon196/tcpsvr
        environment:
            - PORT=3090
        container_name: sam-server


networks:
    net1:
        name: net1
        driver: bridge
